# 2.5.1 Arrays

In [1]:
# Load NumPy package
import numpy as np

In [3]:
# Create two-dimensional array
myArray = np.array([[10, 20, 30], [210, 220, 230]])

In [5]:
# Display the array
myArray

array([[ 10,  20,  30],
       [210, 220, 230]])

In [7]:
# Display the shape
myArray.shape

(2, 3)

In [9]:
# Display the size
myArray.size

6

In [11]:
# Access the second row and third column
myArray[1, 2]

230

In [13]:
# Access the first row
myArray[0, :]

array([10, 20, 30])

In [15]:
# Access the first row's size
myArray[0, :].size

3

## 2.5.2 Array functions

In [18]:
# Create array
array1 = np.array([['a', 'a'], ['b', 'b'], ['c', 'c']])

In [20]:
# Insert 'z's in row 3
np.insert(array1, 3, 'z', axis=0)

array([['a', 'a'],
       ['b', 'b'],
       ['c', 'c'],
       ['z', 'z']], dtype='<U1')

## 2.5.3: Shape functions 

In [23]:
# Create an array
array1 = np.array([[1, 2], [3, 4]])
array1

array([[1, 2],
       [3, 4]])

In [25]:
# Return a flattened array
np.reshape(array1, (1, 4))

array([[1, 2, 3, 4]])

In [27]:
# Create another array
array2 = np.array([[1, 2], [3, 4], [5, 6]])
array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# Return a flattened array
np.ravel(array2)

array([1, 2, 3, 4, 5, 6])

In [31]:
# Resize array to a 2 by 3 array
np.resize(array2, (2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Transpose the array
np.transpose(array2)

array([[1, 3, 5],
       [2, 4, 6]])

## 2.5.4: Math operators and functions

In [36]:
# Create array1
array1 = np.array([[1, 2], [3, 4]])
array1

array([[1, 2],
       [3, 4]])

In [38]:
# Create array2
array2 = np.array([[5, 6], [7, 8]])
array2

array([[5, 6],
       [7, 8]])

In [40]:
# Add array1 and array2
array1 + array2

array([[ 6,  8],
       [10, 12]])

In [42]:
# Subtract array1 and array2
array1 - array2

array([[-4, -4],
       [-4, -4]])

In [44]:
# Multiply array1 and array2
array1 * array2

array([[ 5, 12],
       [21, 32]])

In [46]:
# Divide array1 by array2
array1 / array2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
# Find square root of array 2 elements
np.sqrt(array2)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [50]:
# Find the dot product of rows of array1 and columns of array2
np.dot(array1, array2)

array([[19, 22],
       [43, 50]])